
#开发环境配置
server:
  #服务端口
  port: 8082
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 620
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
#日志配置
logging:
  level:
    com.devin: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
#Spring配置
spring:
  messages:
    #国际化资源文件路径
    basename: i18n/messages
    encoding: utf-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    include: druid,sysparams
  #文件上传
  servlet:
     multipart:
       max-file-size:  1MB
       max-request-size:  1MB
  devtools:
    restart:
      #热部署开关
      enabled: true
  #redis 缓存
  redis:
    host: 192.168.169.43
    port: 16379
    password:
    database: 6
    jedis:
      pool:
        max-idle: 300
        max-active: 1024
        max-wait: 10000
    timeout: 10000
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.devin.project
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /uwin/article/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/uwin/*
# 代码生成
snowflake:
  datacenterId: 1
  workerId: 20
  isUseSystemClock: true
beantalk:
  host: 192.168.169.44
  port: 11300
#转账private Key
callback:
  rsa:
    thirdPrivateKey: MIIEogIBAAKCAQEAt0HPQr3sRqy3mHGyh8mvgfDdjG6c06hosW+MaQddkjJ7SBoJaZvwYtyosJxaPDQntZMloQNDy+o3U7aRmwpHLoAuK76AV/xtcIdhBZKdeJVd3PhRNshmjs66ycEjN71c3vaGVYo/i/4CMzhBUulW508eiDfDHaf6Ww7aKlhcf0kiIRLZEUwBNAVIGDxIb/Os+xmhDKyaeEYtYZ/icp+z+YgdQQfxhLl6ERjebrddN/ASf2fjl1T/kSpHBmlhP7X6lweNZI9wb83rnqVjHgcBDeX4KvIdjrRwa0UR9bWBwL04/vyk7KoZ0clnb4PJgL3HFmFenL8bv5aBBwz8q1wjjQIDAQABAoIBAFbOcaMn2/hOcFlh4jO4Mc7XjdqrutX3/D+wm05VEtnh18v7qWHBYEk0RSQDrCrAed7k6PowVbkOJU8eODK816MLTNOj1Z/YDu8y8Z52KOmpt2Cor6/Hle0nuAtB1bDdnlRvaoqyhg+GLvycNTVVGrlPHSNhZqdxnoHrsyRD3uzbpn+qom6JRlYi6vw880e/8NNGFzw1xIG22uaJRkBmE03RSJ+D5mht+DGczv0jJnpdQLVm/xYfUUEhdCmQDd/soehzRZ2QWTc7bSfvEN82vCnUeuwNiiPGOok4r4HXbRZyc7uyiS0SCNmyX7Il4ho/nRDtHzF4wZdG2+qm4GfbwPECgYEA2QCfJbcBZGB75pCIn04c32syW7jlxB2HxrLzwz3leyQCmIxaMJjexH3jO4g9zkRlqh2WdXFJMBOS+Ga6YseyfMx5orknOeSyZ5LtoCQx+PAZ8Q+HKQdy6H89TKM9yRTI9Pso+S+a1F7ZD4G32BbEXb3tQkbF3r/kke84eYs+3HsCgYEA2DC0VbKHqVUouXF4W1jEKVWHMk8Evr29ArmWzory3EceWlAaD9pNjzdnHAouMJm5OMMgqEJ+JKfB0I+/9AM5eTKDxeq5Eggu15H3e5wOy1pBBVq+++f/zg23BDRcWi+aVFM0PrmR2ET2qkoLPXG+oxk8Q+4R4tltoLUMdpn2FZcCgYBGT+hBPSnrT0P2MjDChXnffoljpOZ2BCeBX2ySf5TCsKlSqm9yvaW4vx2IpZ15Hzpdw5aD2UAgnscJS6fq58/SliJ3ckzeelbALqBmOjQi+BE/xYtC5RH7eXbwRRh49g4jKtpc22rskwr79kkOcFoSEb81sV7dzQmPq5Z983tbzwKBgBohINquvkjQGyD2vvZDb0oTpUiGVmt7YUngBoMmNh47lkaSIeRCnVcu+g5giJ6lJcbfhqXvi3GAuSMtDKVAcoTcfyK/sOimBotVgBT3kq4vVWaBRk4KB1fvPmyKq5LW6A9DEzB1m1QJWcrRMjSV99WcqjUHpC/H2cEvwLbg+uY3AoGAYA61zCgpqfT2p9FgV6W27Jlc+b4ARqo+6IGzpzRUg2M2/pndJAh9DSx8zFwZJ4pJ8HGg1mdx74nsUNf4DzmPwSJJfcKqpYln3QBREzBufXSLmRslS24aOtUUf47wtMfEIsTpGNUpv7KC4z7237S5p4goW7HspFETH/Bi66y+zzg=
    thirdPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt0HPQr3sRqy3mHGyh8mvgfDdjG6c06hosW+MaQddkjJ7SBoJaZvwYtyosJxaPDQntZMloQNDy+o3U7aRmwpHLoAuK76AV/xtcIdhBZKdeJVd3PhRNshmjs66ycEjN71c3vaGVYo/i/4CMzhBUulW508eiDfDHaf6Ww7aKlhcf0kiIRLZEUwBNAVIGDxIb/Os+xmhDKyaeEYtYZ/icp+z+YgdQQfxhLl6ERjebrddN/ASf2fjl1T/kSpHBmlhP7X6lweNZI9wb83rnqVjHgcBDeX4KvIdjrRwa0UR9bWBwL04/vyk7KoZ0clnb4PJgL3HFmFenL8bv5aBBwz8q1wjjQIDAQAB
    depositPrivateKey: MIICXAIBAAKBgQCrErD4VHiA6eocbuA4g3cDetRlFLOBe9yNInklpfO00gVLXy0NCPg0m6JUPVOq5JjsrmUM0zhtIO5zAwBQbe037kUSaXvrce/HJx5G44CVbgWJbDLhsb8/RnyfqjcMNx9ieGHNT0sTngpjLbjbKg+1MGWSwAID1oDNaxqXc+eJOwIDAQABAoGAYMslmIxq1j4DuWy+rxsrRqvD6yFoY5YKd0yPEU8xchj25+uFGP//N/zrPxCn+2R2ZkxSXoxQO+bLJAYJsnhQJE05zPBSzDFhI4I83G0In03egDA2hXAAz9YxB1PF2U1DDwY6qr4EgjHKoCfjfx+L2+Eav2qz5CBrcX7Q0c71kfkCQQDbKa9srTIC4BnO7bLKcriSSBVaDUAVMOo8vjd24RVimuLXyg/NhsqSAWx3TYkv6GAGNugSIcAsN0G8EcxogvflAkEAx9PCMK142PacNObgNMXI4Bc+b+xjKbrsymNz5Z5Si+MV6g0lhZUzLjsV8RxhzOY6ExIoRSZsBc6d+Fm/8BQqnwJAG+IX0YnPfRIp9mvDfYJO/T1yifx5lLiedI/22ocUg3EVP0MT86Ackargs+UHeTLlVKUTrYrhuj5lfJn/GaTgCQJBAKbcT6qgIGpju1p9c7j9c1iUcEG7ja559WKnG08hHmLLNDBl2/Ao/zzaf97/STd1BAeKwO/FPqy2tLh+EUVjQZcCQBSbjHq6ctNMhmMgEpfoJ4Iw6q/17BwcdKdlgcT0L55l9jx0ol9oOZt7d+vch0x7lXxlSVcZeiN91YAWh1Icql8=
    depositPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrErD4VHiA6eocbuA4g3cDetRlFLOBe9yNInklpfO00gVLXy0NCPg0m6JUPVOq5JjsrmUM0zhtIO5zAwBQbe037kUSaXvrce/HJx5G44CVbgWJbDLhsb8/RnyfqjcMNx9ieGHNT0sTngpjLbjbKg+1MGWSwAID1oDNaxqXc+eJOwIDAQAB
    thirdDepositPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCutVCtsb1YhxaN6Z68NCpfFzNJH/uKtm/YqxUt6Avs1OuMLGRf69yoybVndevoild2S5jtbzXISIIMIapYHBsun3Y18sU/c/+NTeO9EZq3vzjyScmPqQHuOm4vCxS7lzDBddM+UxXqy8wVCc5zP721bUVjVVDzH1jjQ7yhG9Ea1wIDAQAB
ftp:
  ip: 192.168.169.113
  port: 3344
  username: devin
  password: devin123!
sysparams:
  huanjing: test
  templateUrl: E://data
  frontWebsocketUrl: http://127.0.0.1:8029/honggong
open:
  defaultDesKey: B3Lbaw6T
ypay:
  platId: 105
  token: 123456
  secretKey: fInANCEY#KEY@1&9)1
  host: http://13.78.22.211:19012/finance

ds:
  # linux需要so
  dynamicPath: E:\data\java\demo\src\main\java\com\demo\nativeTest\jnaTest\cpp\ds.dll
