
#开发环境配置
server:
  #服务端口
  port: 8082
  servlet:
    # 项目contextPath
    context-path: /uwin
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
#日志配置
logging:
  level:
    com.devin: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
#Spring配置
spring:
  messages:
    #国际化资源文件路径
    basename: i18n/messages
    encoding: utf-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    include: druid,sysparams
  #文件上传
  servlet:
     multipart:
       max-file-size:  1MB
       max-request-size:  1MB
  devtools:
    restart:
      #热部署开关
      enabled: true
  #redis 缓存
  redis:
    host: 192.168.169.43
    port: 16379
    password:
    database: 6
    jedis:
      pool:
        max-idle: 300
        max-active: 1024
        max-wait: 10000
    timeout: 10000
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.devin.project
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /uwin/article/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/uwin/*
# 代码生成
snowflake:
  datacenterId: 1
  workerId: 20
  isUseSystemClock: true
beantalk:
  host: 192.168.169.43
  port: 11300